# Generated by Django 4.1.7 on 2023-05-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_ar',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_ar',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_en',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='name_ar',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
